# Generated by Django 4.1.4 on 2022-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_userx_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='cancel_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='donation_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
